version: "3.8"

volumes:

  ckan_data:
  pg_data:
  solr_data:

networks:
  frontend:
  backend:


services:

  # Caddy ---------------------------------------------------------------------
  # CKAN ----------------------------------------------------------------------
  # PostGIS -------------------------------------------------------------------
  db:
    container_name: ${POSTGRESQL_CONTAINER_NAME}
    image: postgres:${POSTGRES_VERSION:?POSTGRES_VERSION not set}
    restart: unless-stopped
    networks:
      - backend
    # ports:
    #  - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
      - postgis//docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:?POSTGRES_USER not set} -d ${POSTGRES_DB:?POSTGRES_DB not set}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    environment:
      PGDATA: /var/lib/postgresql/data/db
      POSTGRES_DB: ${POSTGRES_DB:?POSTGRES_DB not set}
      POSTGRES_USER: ${POSTGRES_USER:?POSTGRES_USER not set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD not set}
      DATASTORE_DB_NAME:
      DATASTORE_DB_RW_USERNAME:
      DATASTORE_DB_RW_PASSWORD:
      DATASTORE_DB_RO_USERNAME:
      DATASTORE_DB_RO_PASSWORD:
      DATAPUSHER_DB_NAME:
      DATAPUSHER_DB_USERNAME:
      DATAPUSHER_DB_PASSWORD:


  db:
    container_name: ${POSTGRESQL_CONTAINER_NAME}
    build:
      context: postgresql/
      args:
       - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    environment:
      - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}


    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ckan"]
  # Solr ----------------------------------------------------------------------

  solr:
    container_name: ${SOLR_CONTAINER_NAME}
    image: ckan/ckan-solr:${SOLR_IMAGE_VERSION}
    volumes:
      - solr_data:/var/solr
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://localhost:8983/solr/"]

  # Redis ---------------------------------------------------------------------
  redis:
    container_name: ${REDIS_CONTAINER_NAME}
    image: redis:${REDIS_VERSION}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-e", "QUIT"]

  # Datapusher ----------------------------------------------------------------
  datapusher:
    container_name: ${DATAPUSHER_CONTAINER_NAME}
    image: ckan/ckan-base-datapusher:${DATAPUSHER_VERSION}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://localhost:8800"]
